apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: apps
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      monitor: apps-monitor
  resources:
    requests:
      memory: 200Mi
  enableAdminAPI: false